name: travelapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  card_swiper:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
     - lib/assets/profileT.jpg
     - lib/assets/1.jpg
     - lib/assets/2.jpg
     - lib/assets/3.jpg
